### ISSUE TITLE
Running on M1 fails to start

### ISSUE THREAD

**Issue by JKetelaar** [brotandgames/ciao#130]
**Describe the bug**
Run the command on a MacBook M1 (Max)
```
docker run --name ciao -p 8090:3000 brotandgames/ciao
```

**To Reproduce**
1. Ensure Docker is running
2. Execute `docker run --name ciao -p 8090:3000 brotandgames/ciao`
3. See error

**Expected behavior**
No error and running

**Desktop (please complete the following information):**
 - OS: MacOS 12.3

**Additional context**
Log: https://gist.github.com/JKetelaar/5c3dc81ebfc40e6b9517281212ac9a36

**Comment by brotandgames** [comment]
Hi @JKetelaar,

Could you please try with the new 1.7.1 docker image?

`docker run --name ciao -p 8090:3000 brotandgames/ciao:1.7.1`

**Comment by JKetelaar** [comment]
Works like a charm! Thanks!
