### ISSUE TITLE
webhook is no work

### ISSUE THREAD

**Issue by seth-shi** [brotandgames/ciao#133]
**Describe the bug**
webhook is no work

**To Reproduce**
my docker-compose file
version: "3"
services:
  ciao:
    image: brotandgames/ciao
    container_name: status_ciao
    ports:
      - '8090:3000'
    environment:
      - SECRET_KEY_BASE=seth
      - TIME_ZONE=PRC
      - BASIC_AUTH_USERNAME=xxxx
      - BASIC_AUTH_PASSWORD=xxxxx
      - CIAO_WEBHOOK_ENDPOINT_1=http://172.27.0.13:9000/wecomchan
      - CIAO_WEBHOOK_PAYLOAD_1={"sendkey":"5660bcd256ba0012c41d3d6f22c17472","msg_type":"text","msg":"[__name__](__url__){__check_url__} Status changed from (__status_before__) to (__status_after__)"}
      - CIAO_LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/db/sqlite/

****
after do no work, fail site status, no WEBHOOK request send

**Comment by brotandgames** [comment]
Are you still having this problem? If so, could you please add logs from ciao?
