### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by fdegraeve** [brotandgames/ciao#14]
How we configure the timezone ?

I try to map with a volume "/etc/localtime" but is not working.

**Comment by brotandgames** [comment]
Currently there is no possibility to set a custom timezone. It is set per default to UTC.
Setting a custom timezone through an ENVIRONMENT variable `TIME_ZONE` will be possible in the next release coming by next week.

**Comment by brotandgames** [comment]
Released earlier than expected. Since version `1.2.0` you can configure a custom time zone (see README.md).
