### ISSUE TITLE
*/15 cron syntax not working

### ISSUE THREAD

**Issue by westonganger** [brotandgames/ciao#15]
Apparently ciao doesnt support the following cron format. 

Ex. run something every 15 minutes

```
*/15 * * * *
```

**Comment by brotandgames** [comment]
Can you provide a screenshot of ciao not working with `*/15 * * * *` cron syntax?

Test:
<img width="801" alt="grafik" src="https://user-images.githubusercontent.com/43862266/61975177-bd04e980-afe8-11e9-9789-986251c2e52b.png">
<img width="794" alt="grafik" src="https://user-images.githubusercontent.com/43862266/61975207-cee68c80-afe8-11e9-8d6c-84f26b161304.png">
