### ISSUE TITLE
Disable TLS expiration notifications

### ISSUE THREAD

**Issue by mignz** [brotandgames/ciao#153]
**Is your feature request related to a problem? Please describe.**
I'm constantly receiving dozens of emails regarding TLS expiration of my services. I can't renew these certificates manually and most are self-signed and automatically generated/renewed.

**Describe the solution you'd like**
An option to disable the feature and/or the notification per Check.

**Comment by brotandgames** [comment]
From version [1.9.3](https://github.com/brotandgames/ciao/releases/tag/1.9.3) onwards you can use the ENV variable `SMTP_DISABLE_TLS_EXPIRES_NOTIFICATIONS=true` to disable TLS expiration notifications via E-Mail.
