### ISSUE TITLE
Can not send email using Ciao

### ISSUE THREAD

**Issue by ramm8469** [brotandgames/ciao#157]
**Describe the bug**
Hi, I'm using the below docker-compose config, out of which I'm able to receive the status updates on web-hook but unable to get status update on email, could anyone please navigate whether it's a configuration issue or a bug..

my docker-compose look similar to this:

 version: "3"
services:
  ciao:
    image: brotandgames/ciao
    container_name: ciao
    ports:
      - '8090:3000'
    environment:
      - CIAO_LOG_LEVEL=DEBUG
      - BASIC_AUTH_USERNAME=jhon
      - BASIC_AUTH_PASSWORD=doe
      - SECRET_KEY_BASE=sensitive_secret_key_base
      - SMTP_ADDRESS=mail.hostname.com
      - SMTP_EMAIL_FROM="admin@hostname.com"
      - SMTP_EMAIL_TO="someone@gmail.com"
      - SMTP_PORT=465
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=mail.hostname.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_USERNAME="admin@hostname.com"
      - SMTP_PASSWORD="your-secret-password"
      - SMTP_SSL=true
      - CIAO_WEBHOOK_ENDPOINT_ROCKETCHAT=https://webhook.site/xxxx-xxxx-xxxx
      - CIAO_WEBHOOK_PAYLOAD_ROCKETCHAT={"name":"__name__", "status_before":"__status_before__", "status_after":"__status_after__", "check_url":"__check_url__", "url":"__url__"}
    volumes:
      - /opt/ciao/data:/app/db/sqlite/

**To Reproduce**
1. Pull docker compose
2. docker-compose up -d 
3. add any http url and test

**Expected behavior**
It should also send email on status updates

**Screenshots**

![image](https://github.com/brotandgames/ciao/assets/38792978/1006db31-1d86-46cf-ad17-0f348beca443)

**Comment by brotandgames** [comment]
Could you please add the whole error message as `code` or attachment (without sensitive information if any)?

**Comment by brotandgames** [comment]
Closed as stale.
