### ISSUE TITLE
Feature request - history for a given URL

### ISSUE THREAD

**Issue by zeornelas** [brotandgames/ciao#23]
First of all congratulations for this tool.

It might be useful to have an history of calls made for each of the checks/URL.

**Comment by brotandgames** [comment]
Having a history is not in the scope for this project.

However, it is planned to have a Prometheus endpoint `/metrics` in the future (on the Roadmap) where the metrics of all checks will be exposed. 
You could then poll these Metrics with Grafana and build a Dashboard with History etc.

**Comment by zeornelas** [comment]
> However, it is planned to have a Prometheus endpoint `/metrics` in the future (on the Roadmap) where the metrics of all checks will be exposed.
> You could then poll these Metrics with Grafana and build a Dashboard with History etc.

Perfect, that would be very useful!
