### ISSUE TITLE
Add option to turn off endpoint SSL/TLS certificate verification

### ISSUE THREAD

**Issue by mahdi-hosseini** [brotandgames/ciao#28]
Thanks for making this available, it is a nice replacement for my homebrew Go-based pinger that I have been using.

I run some services that are for internal use and are either self-signed certified or signed by a local certificate authority and I would like to have the option to turn off certificate verification. Right now the endpoint check fails when it is unable to verify. It would be nice to have a checkbox that disables certificate verification per endpoint.

The error I encounter is as follows which causes the check to fail:
```SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)```

**Comment by tareksamni** [comment]
This should be an easy to implement feature. I will open a PR today with the changes.

**Comment by brotandgames** [comment]
@mahdi-hosseini Suppose you are using Docker to deploy ciao.
If the certificate store on the host is compatible with the guest (Docker container based on alpine Docker image), you can just mount it:
````
docker run --name ciao \
  -p 8090:3000
  -v /etc/ssl/certs:/etc/ssl/certs:ro
  brotandgames/ciao
````
Would this solution work for you?

**Comment by brotandgames** [comment]
@mahdi-hosseini If the host is not compatible with the guest you would have to mount the cert into `/usr/local/share/ca-certificates` and run `update-ca-certificates`before `./start.sh` like
````
docker run --name ciao \
  -p 8090:3000 \
  -v /path/to/certs:/usr/local/share/ca-certificates \
  brotandgames/ciao \
  update-ca-certificates && ./start.sh
````

**Comment by tareksamni** [comment]
@brotandgames I think we should change:
```
CMD ["./start.sh"]
```

in the docker file to:

```
ENTRYPOINT ["./start.sh"]
```

Then he could run:

```
docker run --name ciao \
  -p 8090:3000 \
  -v /path/to/certs:/usr/local/share/ca-certificates \
  brotandgames/ciao \
  update-ca-certificates
```

Which will run the passed CMD `update-ca-certificates` and the entrypoint as well `start.sh`

**Comment by tareksamni** [comment]
@brotandgames https://github.com/brotandgames/ciao/pull/29 this is a simple change and provides more flexibility to target this issue.

**Comment by brotandgames** [comment]
@tareksamni 
From [StackOverflow](https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile):
> ENTRYPOINT should be defined when using the container as an executable

or 

>The ENTRYPOINT specifies a command that will always be executed when the container starts. The CMD specifies arguments that will be fed to the ENTRYPOINT.

Would leave it as it is and what's wrong with just simply overriding the CMD?

**Comment by tareksamni** [comment]
I use `ENTRYPOINT` as an "entry point" to bootstrap the environment for the application to run. For ex. to `rake db:migrate` or run any other dependencies. and then execute the CMD afterwords. This is a good practice and most of the docker public images are doing the same. It's not delivering or preventing and immediate value in our project now but it's a good practice to isolate the actual command "rails s" and any other work to happen before "bootstrap".

**Comment by brotandgames** [comment]
> This is a good practice and most of the docker public images are doing the same.

Don't agree. [Here](https://blog.codeship.com/understanding-dockers-cmd-and-entrypoint-instructions/) you can find a nice explanation.

**Comment by tareksamni** [comment]
This explanation is exactly what I understand about `CMD` and `ENTRYPOINT` and that's why I was recommending using the `ENTRYPOINT`. It's offtopic anyway :)

Just examples from the open-source community:

https://github.com/docker-library/postgres/blob/master/Dockerfile-alpine.template
https://github.com/docker-library/redis/blob/master/5.0/Dockerfile
https://github.com/docker-library/rabbitmq/blob/master/Dockerfile-alpine.template
https://github.com/docker-library/mongo/blob/master/4.1/Dockerfile

**Comment by brotandgames** [comment]
In your examples the `ENTRYPOINT` is used in another way than in the explanation above.
As you stated: it's off-topic anyway ;) 

Want to keep the `start.sh` as it is and if someone needs to overwrite the `CMD` it's simple as shown [here](https://github.com/brotandgames/ciao/issues/28#issuecomment-517901990).

**Comment by brotandgames** [comment]
@mahdi-hosseini Did any of the solutions ([one](https://github.com/brotandgames/ciao/issues/28#issuecomment-517901389), [two](https://github.com/brotandgames/ciao/issues/28#issuecomment-517901990)) work for you?

**Comment by mahdi-hosseini** [comment]
Yes, thank you for providing those tips!
