### ISSUE TITLE
Add an option to mark redirects as healthy

### ISSUE THREAD

**Issue by TheGamingBarrel** [brotandgames/ciao#31]
For a lot of the services I run they redirect you to a login page or a dashboard if you're logged in etc, a feature to set redirects as a "healthy" option, hopefully per-check so that they don't appear as unhealthy in the overview would be greatly appreciated; if not just for reducing the heart attacks I have.

![1564869749](https://user-images.githubusercontent.com/9117223/62417236-ea821080-b642-11e9-821c-25ab47ea1353.png)

Loving the project, it's entirely possible I'm missing a config option or something though.

**Comment by brotandgames** [comment]
There are no plans for a feature to set redirects as healthy. A check is per se only healthy if it returns something in the 2xx range.
Are there no options to set your url(s) to something that returns 2xx?

Btw. there are plans to have something like this in the overview/dashboard of ciao:

<img width="598" alt="grafik" src="https://user-images.githubusercontent.com/43862266/62421951-ac203c00-b6aa-11e9-804b-d95a17af00c7.png">

Would this reduce the heart attacks you have?

**Comment by TheGamingBarrel** [comment]
That would be a great addition not just for me but to quickly understand issues when you first load it up and I like the idea, I'll have a look at implementing a page on the services I control that doesn't get redirected though to help myself :P 

Thanks, the HTTP Status overview provides enough clarity that I think I can close this and look forward to the update where this comes.

**Comment by brotandgames** [comment]
@TheGamingBarrel Thank you for your inspiration to clarify what healthy and unhealthy means.

> HTTP Status overview provides enough clarity

![grafik](https://user-images.githubusercontent.com/43862266/62431743-5ee3af00-b72a-11e9-90f4-b589f22cc601.png)

Here it is and it will be available with the next release.

**Comment by brotandgames** [comment]
@TheGamingBarrel Released with 1.6.0.
