### ISSUE TITLE
Feature Request - Dashboard for multiple environments

### ISSUE THREAD

**Issue by cbzxt** [brotandgames/ciao#4]
First of this is a really great tool. Thank you for creating it. I am using it for some time now and I have ~ 100 urls. We have 20 end points for 1 environment and total 5 environments.  Is there any possibility of implementing a dashboard feature where we can have tabs for each environment?

**Comment by sebbean** [comment]
open a PR! @cbzxt

**Comment by brotandgames** [comment]
This is not in the scope of the project.
