### ISSUE TITLE
SMTP_ENABLE_STARTTLS_AUTO should be a boolean

### ISSUE THREAD

**Issue by jasonadamyoung** [brotandgames/ciao#47]
Hi!  I'm trying to setup ciao on a homelab kubernetes cluster - where I already have an in-house open mail relay that's just doing doing raw port 25, no-ssl (and in turn relays to an actual authenticated provider).

As far as I'm aware, the Action Mailer 'enable_starttls_auto' should be a boolean value - the docs indicate 'auto' which I don't think is valid (and thereby it just defaults to true in action_mailer).  Setting it to false in the environment values (or helm values) just has it end up as a "false" string in the actual rails configuration.

I'm guessing it needs the same ActiveModel::Type::Boolean.new.cast casting that ENV['SMTP_SSL'] received.

I can submit a PR - but haven't set up a ciao development environment - and figured this might just be easier as a quick issue report.

**Comment by brotandgames** [comment]
@jasonadamyoung Thanks for reporting.

Fixed and updated the README.
