### ISSUE TITLE
Bootstrap from Configuration file

### ISSUE THREAD

**Issue by warmfusion** [brotandgames/ciao#5]
Can this be deployed using a config file and put into a 'read-only' mode so that it may be deployed as part of a CI/CD flow onto infrastructure without needing to worry about managing state and backups etc.

I'd like to deploy this service onto a Kubernetes environment where we declare the endpoints using a configuration file (eg yaml) for all the endpoints, then changes to sites etc would be a redeployment of the services ConfigMap.

Ideally the service would then recognise the configfile change and reload without losing existing state data.

**Comment by tareksamni** [comment]
@warmfusion, Would this wipe the database and reinitiate it from the `yaml` file on every restart?

If you could confirm, I think this is very much easily doable and I'd love to implement it :)

**Comment by warmfusion** [comment]
As mentioned, ideally the configfile changes would be recognised dynamically (as configmap modifications change files on disk without notification to running services on kubernetes) such that configs are reloaded and any existing check states are maintained.

The use of a local SQLite database means on kube a volume claim could be used and mounted to provide persistence between instances, so even in the 'worst' case where the pods are fully restarted on config changes, the data would be maintained.

The PR you've mentioned provides a good starting point, and i've added some comments there for some specific consideration.

👍

**Comment by brotandgames** [comment]
Closed this Issue because of inactivity.
