### ISSUE TITLE
Telegram webhooks issue

### ISSUE THREAD

**Issue by VadzimTarasiuk** [brotandgames/ciao#50]
**Describe the bug**
I don't get any notifications from TG webhooks set as env variables in docker-compose.yml
```
CIAO_WEBHOOK_ENDPOINT_TELEGRAM="https://api.telegram.org/bot<TG-bot-auth-tocken>/sendMessage"
CIAO_WEBHOOK_PAYLOAD_TELEGRAM='{"chat_id":<chat-room-id>,"disable_web_page_preview":1,"text": "[__name__] Status changed from (__status_before__) to (__status_after__)"}'
```

When checked with curl I found 
```
{"ok":false,"error_code":400,"description":"Bad Request: message text is empty"} response.
```
The command was pretty plain:
```
curl -X POST https://api.telegram.org/bot<TG-bot-auth-tocken>/sendMessage"  -d '{"chat_id":<chat-room-id>,"disable_web_page_preview":1,"text": "[__name__] Status changed from (__status_before__) to (__status_after__)"}'
```

The messages are sending correctly when specify the json-content Header:
```bash
curl -X POST https://api.telegram.org/bot<TG-bot-auth-tocken>/sendMessage"  -d '{"chat_id":<chat-room-id>,"disable_web_page_preview":1,"text": "[__name__] Status changed from (__status_before__) to (__status_after__)"}' -H 'Content-Type: application/json'
```

Could it be that I was needed to specify more params in docker-compose file to make notifications working?

**Comment by finneon** [comment]
Check this https://github.com/brotandgames/ciao/issues/40

**Comment by VadzimTarasiuk** [comment]
Great, thanks @finneon! 
To be more precise I removed quotes at all as below and it worked.
```
CIAO_WEBHOOK_ENDPOINT_TELEGRAM=https://api.telegram.org/bot<TG-bot-auth-tocken>/sendMessage
CIAO_WEBHOOK_PAYLOAD_TELEGRAM={"chat_id":<chat-room-id>,"disable_web_page_preview":1,"text": "[__name__] Status changed from (__status_before__) to (__status_after__)"}
```
Confusingly simple. Sorry for any troubles caused and have a nice day :)

**Comment by brotandgames** [comment]
@VadzimTarasiuk @finneon Both solutions are wotking with `docker-compose`.
FYI There is also a note in the docs: https://github.com/brotandgames/ciao/blob/master/webhook_configuration.md#notes
