### ISSUE TITLE
Unable to run ciao on raspberry pi using docker

### ISSUE THREAD

**Issue by obromios** [brotandgames/ciao#53]
**Describe the bug**
When I try to run ciao on a raspberry pi using docker, I see a linux error. I did not encounter the same problem on OSX

**To Reproduce**
After installing docker on a raspberry pi and then running ciao with
`
docker run --name ciao -p 8090:3000 brotandgames/ciao
`
I see the following error:
`standard_init_linuz.go:211 eexec user process caused "exec format error"
`

**Expected behavior**
When I ran the same command on OSX, ciao started as requested, and I found it so useful, that I want to run it 24/7 on a rapsberry pi.

**Desktop (please complete the following information):**
The operating system is Raspbian GNU/Linux, version 10 (buster).
It is running on a raspberry pi 3 model B

**Comment by brotandgames** [comment]
@obromios There is currently no Docker build for ciao on Arm.

We are open for PRs.

**Comment by nexeduapp** [comment]
Try this one

https://hub.docker.com/repository/docker/emaderito/ciao-rpi

**Comment by abuisman** [comment]
You can build the image on your raspberry. I needed to make some changes before it would build to begin with:

https://github.com/brotandgames/ciao/pull/93

**Comment by brotandgames** [comment]
Ciao (> 1.6.13) is now available for arm/v7 and arm64:

https://hub.docker.com/r/brotandgames/ciao/tags

![grafik](https://user-images.githubusercontent.com/43862266/145879326-ddf1ae26-bc2e-4a8a-8d66-f5b698716e8f.png)
