### ISSUE TITLE
Persistent Storage Setup with Docker

### ISSUE THREAD

**Issue by gnomus** [brotandgames/ciao#6]
Currently the Database is stored withing the Container itself which means you loose all Data if your Container dies and the Orchestrator creates a new one.
This also prevents all Users from updating without loosing all Data.

Please move the Production SQLite into a Volume or provide an easy way to use MySQL/PostgreSQL

**Comment by brotandgames** [comment]
As of now you won't loose your data if you backup the internal SQLite database in a certain interval.
A backup and restore (after crash, update) method could look something like this using Docker.
````
# Backup
docker cp ciao:/app/db/production.sqlite3 production.sqlite3.backup

# Restore
docker cp production.sqlite3.backup ciao:/app/db/production.sqlite3
docker restart ciao
````
If you are using Kubernetes kubectl offers similar options.

It is planned to move the internal database into a Volume and a Helm Chart for Kubernetes is in development. Help would be appreciated.

**Comment by brotandgames** [comment]
SQLite DB is stored in a subfolder `db/sqlite/` and the `VOLUME /app/db/sqlite` directive has been added to the Dockerfile to enable Docker volume usage. Merci @gnomus 

Added Backup & Restore and Upgrade instructions in README.md.
