### ISSUE TITLE
Favicon proposition

### ISSUE THREAD

**Issue by PurpleBabar** [brotandgames/ciao#60]
Hey :) 

Thanks for ciao, it's really simple and i love to use it ! :D 
The only thing is I can't identify quickly ciao in a browser since there's no favicon :/ So i propose this favicon :) (I can send you the svg version if you'd like ;) )
![favicon-32x32](https://user-images.githubusercontent.com/7846095/66479433-c7d60300-ea9c-11e9-95f0-0f7d2a919672.png)

cheerz :)

**Comment by brotandgames** [comment]
@PurpleBabar Thanks for your submission. Currently we are looking for a logo for ciao and the favicon should be similar :)
Can we chat on gitter?

**Comment by PurpleBabar** [comment]
Yup :) I'm available there :)

**Comment by brotandgames** [comment]
Added basic favicon in https://github.com/brotandgames/ciao/commit/22e7340d545adb58e97174d479351110c80aba8e just to make ciao more visible in between open tabs.
