### ISSUE TITLE
socks5 proxy

### ISSUE THREAD

**Issue by bykvaadm** [brotandgames/ciao#61]
**Describe the solution you'd like**
Please add ability to send outcoming requests via [socks5] proxy

my workaround was to modify start.sh to run proxychains-ng, and it works fine

**Comment by bykvaadm** [comment]
my workaround was to modify start.sh to run proxychains-ng, and it works fine

**Comment by brotandgames** [comment]
@bykvaadm This is not in the scope of this project.
