### ISSUE TITLE
Access via SSL HTTPS

### ISSUE THREAD

**Issue by vinaykapadia** [brotandgames/ciao#72]
**Is your feature request related to a problem? Please describe.**
I can only access Ciao via HTTP.

**Describe the solution you'd like**
I can access Ciao via HTTPS and give it a certificate to use.

**Describe alternatives you've considered**
A reverse proxy maybe, but that seems excessive.

**Comment by brotandgames** [comment]
Hi @vinaykapadia,
It's not in the scope of this project to manage SSL/TLS certificates. You can use a reverse proxy like nginx, Traefik etc. for SSL/TLS offloading.
