### ISSUE TITLE
Relative Path

### ISSUE THREAD

**Issue by allenlyk** [brotandgames/ciao#74]
**Is your feature request related to a problem? Please describe.**
I am currently hosting Ciao at xxx.com/yyyy/ . The /checks (and other page links in the page) and links to css/js/woff/tiff seems not relative. Because even though I am able to make the page load at xxx.com/yyyy/ but the /checks and css/js/woff/tiff still refers to xxx.com/checks for example.

**Describe the solution you'd like**
Make the paths relative so that it can be hosted in domain subdir

**Comment by brotandgames** [comment]
This feature is not in the scope of this project.
