### ISSUE TITLE
Timeout setting for checking

### ISSUE THREAD

**Issue by Alex-Beta** [brotandgames/ciao#75]
i'm often recived message from ciao like below while the service is not broken
`domain checker, [07.05.20 08:46]
[test.domain.com] Status changed from (200) to (execution expired)}

domain checker, [07.05.20 08:46]
[test.domain.com] Status changed from (execution expired) to (200)}`

I assume that this is due to the remoteness of the web server from the ciao service

I would like to set the connection timeout setting

In last 1 day i recived 500+ messages from 4 services in monitoring. They were all false positives

**Comment by PhrantiK** [comment]
I'm getting false positives too:

Email:

from: 200 
to: Failed to open TCP connection to mydomain.com:443 (getaddrinfo: Try again) 

From the container:

~ # wget -S https://mydomain.com -O /dev/null
Connecting to mydomain.com (x.x.x.x:443)
  HTTP/1.1 200 OK

**Comment by sebw** [comment]
Same. I'm running ciao to monitor neighbouring containers. For one container I have to monitor through the frontend (backend service is on a selfsigned cert) and this fails a lot multiple times a day.

Same goes for my NAS monitoring that was almost never failing with statping. Every day I get multiple false positives.

**Comment by brotandgames** [comment]
@Alex-Beta _Connection timeout setting_ is not in the scope of this project.

**Comment by sebw** [comment]
No offense intented but what is actually in the scope of this project? Because connection timeout tuning or disabling TLS verifications are valid use cases in the real world.

**Comment by Alex-Beta** [comment]
So how do i avoid false positive alerts stay _in the scope of this project_?
