### ISSUE TITLE
error converting YAML to JSON: yaml: line 12: did not find expected key

### ISSUE THREAD

**Issue by Jimmyjim123** [brotandgames/ciao#83]
Hello im having trouble running the YAML file. Everytime i run the file, i get an error stating that it did not find expected key.

    `apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: ciao
  namespace: monitoring
data:
  BASIC_AUTH_USERNAME: YWRtaW4=
  BASIC_AUTH_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciao
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
  selector:
      labels:
        app: ciao
    spec:
      containers:
      - image: brotandgames/ciao:latest
        imagePullPolicy: IfNotPresent
        name: ciao
        volumeMounts: # Emit if you do not have persistent volumes
        - mountPath: /app/db/sqlite/
          name: persistent-volume
          subPath: ciao
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 400m
        envFrom:
        - secretRef:
            name: ciao
---
apiVersion: v1
kind: Service
metadata:
  name: ciao
  namespace: monitoring
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: ciao`

**Comment by brotandgames** [comment]
@Jimmyjim123 Did you find a solution for your problem? If not, please open a new Issue (Bug report) with respect to the template and proper formatting. Don't forget to remove any passwords etc. from your logs, code etc.
