### ISSUE TITLE
Gotify Notification not sending.

### ISSUE THREAD

**Issue by limitlessbritt** [brotandgames/ciao#86]
When i try to add gotify as a webhook it doesn't send any messages and I don't see any info about in the logs

here are env settings I used:
CIAO_WEBHOOK_ENDPOINT_GOTIFY=http://gotify.me/message
CIAO_WEBHOOK_PAYLOAD_GOTIFY='{"Content Type":"application/json", "message": "[ciao] __name__: Status changed (__status_after__)", "priority": 2, "title": "Service Check", "token": "token" }'

I'm running docker, not docker compose.

**Comment by vaclandic** [comment]
same issue, but with telegram webhook

**Comment by sebw** [comment]
Works for me by passing the token in the URL:

```
CIAO_WEBHOOK_ENDPOINT_GOTIFY: "https://gotify.example.org/message?token=XYZ"
CIAO_WEBHOOK_PAYLOAD_GOTIFY: '{"title": "status.example.org - __name__","message": "Before: __status_before__\nNew status: __status_after__", "priority": 1}'
```

**Comment by brotandgames** [comment]
@limitlessbritt Does https://github.com/brotandgames/ciao/issues/86#issuecomment-701636196 work for you?

@vaclandic Did you follow the example in https://github.com/brotandgames/ciao/blob/master/webhook_configuration.md#telegram?

@sebw Thanks for posting this Gotify example. You are free to submit a PR with your example configuration.

**Comment by vaclandic** [comment]
i am using nomad for docker orchestration
and for me work this solution:
```bash
CIAO_WEBHOOK_ENDPOINT_TELEGRAM="https://api.telegram.org/bot***/sendMessage"
CIAO_WEBHOOK_PAYLOAD_TELEGRAM="{\"chat_id\": \"****\", \"disable_web_page_preview\": 1, \"text\": \"[__name__] Status changed from (__status_before__) to (__status_after__)\"}"
```

**Comment by juan11perez** [comment]
good day. Anyone has had any luck using gotify with docker compose. I see the note on the post by sebw, but that does not work with compose.
Thank you

**Comment by brotandgames** [comment]
Closed as stale
