### ISSUE TITLE
Can it support monitoring of specified URLs through http or socks proxy?

### ISSUE THREAD

**Issue by xgrei** [brotandgames/ciao#87]
**Is your feature request related to a problem? Please describe.**
Some of the URLs I want to monitor can only be accessed through a proxy

**Describe the solution you'd like**
 such as an undisclosed company internal website

**Describe alternatives you've considered**
No alternatives found yet

**Additional context**
none

**Comment by brotandgames** [comment]
@xgrei This is not in the scope of this project. 

See https://github.com/brotandgames/ciao/issues/61
