### ISSUE TITLE
Disable certificate verification

### ISSUE THREAD

**Issue by sebw** [brotandgames/ciao#88]
I want to monitor things on my home network and some devices use self-signed certificates.

It would be nice to be able to disable certificate validation per check.

**Comment by brotandgames** [comment]
@sebw This is not in the scope of this project.

Possible solution(s) for your usecase: https://github.com/brotandgames/ciao/issues/28#issuecomment-517901389

**Comment by brotandgames** [comment]
Duplicate of #28
