### ISSUE TITLE
Cron does not work correctly at time setting

### ISSUE THREAD

**Issue by vumdao** [brotandgames/ciao#90]
**Describe the bug**
Setting cron to health check daily at specific time setting does not work correctly
![image](https://user-images.githubusercontent.com/37215642/98197788-1f71c700-1f5a-11eb-9399-4c1cd88512a9.png)
![image](https://user-images.githubusercontent.com/37215642/98197820-31ec0080-1f5a-11eb-802e-845de82b5c37.png)

ciao 1.6.10

**Comment by brotandgames** [comment]
Please read the docs: https://github.com/brotandgames/ciao#configuration

> Time zone is configurable per `TIME_ZONE` variable (default: `UTC`) eg. `TIME_ZONE="Vienna"` - you can find all possible values by executing `docker run --rm brotandgames/ciao rake time:zones` (since version 1.2.0)

**Comment by vumdao** [comment]
> Please read the docs: https://github.com/brotandgames/ciao#configuration
> 
> > Time zone is configurable per `TIME_ZONE` variable (default: `UTC`) eg. `TIME_ZONE="Vienna"` - you can find all possible values by executing `docker run --rm brotandgames/ciao rake time:zones` (since version 1.2.0)

@brotandgames As you see I set the time zone is UTC and expect the sc
