### ISSUE TITLE
Feature Request ICMP (Ping) to IP or hostname.

### ISSUE THREAD

**Issue by CorneliousJD** [brotandgames/ciao#95]
**Is your feature request related to a problem? Please describe.**
Right now this is only able to monitor HTTP status, I have plenty of services I would like to monitor that do not have HTTP pages.

**Describe the solution you'd like**
Would like the ability to monitor just if a host is alive with ICMP ping commands, either up if it returns a reponse (perhaps also documenting latency) or down/failed check.

**Describe alternatives you've considered**
I have tried various other selfhosted options like StatPing (buggy and unstable) and Cachet (confusing and frustrating to configure this type of check), and keep coming back to Ciao, but it doesn't support this feature at all.

**Additional context**
I do understand in https://github.com/brotandgames/ciao/issues/37 that it was noted to be outside the scope of this project, just checking back in to see if this might be re-considered at any point.

Thank you for your time.

**Comment by brotandgames** [comment]
ciao is made/designed to check HTTP(S) URL endpoints only thus ICMP (ping) is not in the scope of this project.
